spring:
  application:
    name: order-service
  rabbitmq:
         host: 172.31.101.49
         port: 5672
         username: admin
         password: admin
         virtual-host: /

server:
  port: 9002

